name: Build and Push Docker

on:
  push:
    branches:
      - main

jobs:
  build-push-docker:
    name: Build and push docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push rostov-bot image
        working-directory: ./src/rostov
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rostov-bot:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/rostov-bot:latest

      - name: Build and push metar-bot image
        working-directory: ./src/metar
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/metar-bot:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/metar-bot:latest

      - name: Build and push atc-bot image
        working-directory: ./src/atc
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/atc-bot:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/atc-bot:latest
